//Authentication
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

//Alerts
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//Users
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const REINICIAR = 'REINICIAR'; 
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS'; 
export const ACTUALIZAR_USUARIO = 'ACTUALIZAR_USUARIO';
export const CAMBIAR_ESTADO = 'CAMBIAR_ESTADO';
export const OBTENER_UN_USUARIO = 'OBTENER_UN_USUARIO';

//Brands
export const OBTENER_MARCAS = 'OBTENER_MARCAS';
export const GUARDAR_MARCA_EXITO = 'GUARDAR_MARCA_EXITO';
export const GUARDAR_MARCA_ERROR = 'GUARDAR_MARCA_ERROR';
export const EDITAR_MARCA = 'EDITAR_MARCA';

//Locations
export const GUARDAR_LOCATION_EXITO = "GUARDAR_LOCATION_EXITO";
export const GUARDAR_LOCATION_ERROR = "GUARDAR_LOCATION_ERROR";
export const EDITAR_LOCATION = "EDITAR_LOCATION";
export const OBTENER_LOCATIONS = "OBTENER_LOCATIONS"; 
export const ELIMINAR_UBICACION = "ELIMINAR_UBICACION";
