//Cars
export const GUARDAR_CAR_EXITO = "GUARDA_CAR_EXITO";
export const GUARDAR_CAR_ERROR = "GUARDA_CAR_ERROR";
export const OBTENER_ALL_CAR = "OBTENER_ALL_CAR";
export const EDITAR_CAR = "EDITAR_CAR";
export const OBTENER_UN_CAR = "OBTENER_UN_CAR"; 
export const FILTRAR_CAR_PLATE = "FILTRAR_CAR_PLATE";
export const FILTRAR_CAR_BRAND = "FILTRAR_CAR_BRAND";
export const FILTRAR_CAR_MODEL = "FILTRAR_CAR_MODEL";
export const FILTRAR_CAR_YEAR = "FILTRAR_CAR_YEAR";
export const FILTRAR_CAR_LOCATION = "FILTRAR_CAR_LOCATION";


//Parts
export const GUARDAR_PIEZA_EXITO = "GUARDAR_PIEZA_EXITO";
export const GUARDAR_PIEZA_ERROR = "GUARDAR_PIEZA_ERROR";
export const OBTENER_ALL_PIEZAS = "OBTENER_ALL_PIEZAS";
export const OBTENER_PIEZAS_DE_COCHE = "OBTENER_PIEZAS_DE_COCHE";
export const ACTUALIZAR_PIEZA = "ACTUALIZAR_PIEZA";
export const REINICIAR_PART = "REINICIAR_PART";

//Images
export const ELIMINAR_IMAGE = "ELIMINAR_IMAGE";
export const OBTENER_IMAGES_CAR = "OBTENER_IMAGES_CAR";
export const ERROR_IMAGES = "ERROR_IMAGES";
export const REINICIAR_IMAGES = "REINICIAR_IMAGES"; 

//Sales
export const REALIZAR_VENTA = "REALIZAR_VENTA";
export const REALIZAR_VENTA_ERROR = "REALIZAR_VENTA_ERROR";
export const OBTENER_ALL_VENTAS = "OBTENER_ALL_VENTAS";
export const OBTENER_UNA_VENTA = "OBTENER_UNA_VENTA";
export const REINICIAR_SALE = "REINICIAR_SALE";


//Authentication
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";

//Alerts
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

//Users
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const REINICIAR = "REINICIAR";
export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const ACTUALIZAR_USUARIO = "ACTUALIZAR_USUARIO";
export const CAMBIAR_ESTADO = "CAMBIAR_ESTADO";
export const OBTENER_UN_USUARIO = "OBTENER_UN_USUARIO";
export const CAMBIAR_CONTRASENA = "CAMBIAR_CONTRASENA";

//Brands
export const OBTENER_MARCAS = "OBTENER_MARCAS";
export const GUARDAR_MARCA_EXITO = "GUARDAR_MARCA_EXITO";
export const GUARDAR_MARCA_ERROR = "GUARDAR_MARCA_ERROR";
export const EDITAR_MARCA = "EDITAR_MARCA";
export const OBTENER_UNA_MARCA = "OBTENER_UNA_MARCA";
export const REINICIAR_MARCA = "REINICIAR_MARCA";
export const BUSCAR_MARCA = "BUSCAR_MARCA";

//Locations
export const GUARDAR_LOCATION_EXITO = "GUARDAR_LOCATION_EXITO";
export const GUARDAR_LOCATION_ERROR = "GUARDAR_LOCATION_ERROR";
export const EDITAR_LOCATION = "EDITAR_LOCATION";
export const OBTENER_LOCATIONS = "OBTENER_LOCATIONS";
export const ELIMINAR_UBICACION = "ELIMINAR_UBICACION";
export const REINICIAR_LOCATION = "REINICIAR_LOCATION";
export const BUSCAR_LOCATION = "BUSCAR_LOCATION";

//Shower 
export const MOSTRAR_OCULTAR = "MOSTRAR_OCULTAR";
